export enum Operation {
  POWER = "^",
  ADDITION = "+",
  SUBTRACTION = "-",
  MULTIPLICATION = "*",
  DIVISION = "/",
  FACTORIAL = "!",
  SIN = "sin",
  COS = "cos",
  TG = "tg",
  CTG = "ctg",
  SQR = "sqr",
  SQRT = "sqrt",
  TRUNC = "trunc",
  ROUND = "round",
  UNSUPPORTED_OPERATION = "unsuppoerted",
}
